#+TITLE: Makefile 简介

* 构建系统
  makefile是一种构建系统，种其它环境中常用scons, maven, gradle, meson等是同一类,解决相同的问题。
  构建系统(build system)
  




* $ sign in makefile

It's the dollar sign, in makefiles you'll have to type $$ to get a single dollar sign:

#+BEGIN_EXAMPLE

#+END_EXAMPLE


M_ARCH := $(shell g++ -dumpmachine | awk '{split($$1,a,"-");print a[1]}')


#+END_EXAMPLE
