* kernal module load
** virtualbox
/etc/modules-load.d/virtualbox.conf

#+BEGIN_EXAMPLE

vboxdrv
vboxguest
vboxsf
vboxvideo
vboxnetadp
vboxnetflt


#+END_EXAMPLE


** 
#+BEGIN_EXAMPLE
man modules-load.d
#+END_EXAMPLE

  modules-load.d

 systemd-modules-load.service(8) reads files from the above
       directories which contain kernel modules to load during boot in a
       static list. Each configuration file is named in the style of
       /etc/modules-load.d/program.conf. Note that it is usually a better
       idea to rely on the automatic module loading by PCI IDs, USB IDs, DMI
       IDs or similar triggers encoded in the kernel modules themselves
       instead of static configuration like this. In fact, most modern
       kernel modules are prepared for automatic loading already.
https://wiki.archlinux.org/index.php/Systemd

Troubleshooting

#+BEGIN_EXAMPLE
$ systemctl --failed
$ systemctl status systemd-modules-load
$ journalctl _PID=15630
#+END_EXAMPLE

* hhkb下　disable power键

xev
evtest 查看操作事件



https://unix.stackexchange.com/questions/106468/remapping-power-key-to-delete
** xkb
#+BEGIN_EXAMPLE
key <POWR> { [ prior] } //不管用
#+END_EXAMPLE

keycode = 124

** /etc/systemd/logind.conf

#+BEGIN_SRC 
HandlePowerKey=ignore
#+END_SRC



systemd can handle this. I think this is what you need:

Open the /etc/systemd/logind.conf (manual):

    HandlePowerKey: action on power key is pressed;
    HandleSuspendKey: action on suspend key is pressed.
    HandleHibernateKey: action on hibernate key is pressed.
    HandleLidSwitch: action when the lid is closed.

The action can be one of ignore, poweroff, reboot, halt, suspend, hibernate or kexec.

If no configuration, default values used:

    HandlePowerKey=poweroff
    HandleSuspendKey=suspend
    HandleHibernateKey=hibernate
    HandleLidSwitch=suspend



** Change Behavior of Linux Power Button

https://superuser.com/questions/699905/change-behavior-of-linux-power-button


Well, one thing you could do is simply disable the power button altogether. Personally, I only use it to turn on my machine, and never use it once the machine is on. If this is an OK solution for you, edit /etc/acpi/events/powerbtn-acpi-support:

sudo nano /etc/acpi/events/powerbtn-acpi-support

That file should look something like this:

event=button[ /]power
action=/etc/acpi/powerbtn-acpi-support.sh

To make the power button do nothing, change it to:

event=button[ /]power
action=

Then restart the acpi daemon with

sudo service acpid restart

Your power button should no be ignored.

* virtualbox
** virtual machine
 https://en.wikipedia.org/wiki/Virtual_machine


 在详细介绍之前，有几个概念要说明：
 1. VM（Virtual Machine）——虚拟机，指由Vmware模拟出来的一台虚拟的计算机，也即逻辑上的一台计算机。
 2.HOST——指物理存在的计算机，Host′s OS指HOST上运行的操作系统。
 3. Guest OS——指运行在VM上的操作系统。例如在一台安装了Windows NT的计算机上安装了Vmware，那么，HOST指的是安装Windows NT的这台计算机，其Host′s OS为Windows NT。VM上运行的是Linux，那么Linux即为Guest OS。

*** ArchLinux 下 VirtualBox 增强设置
 http://www.cnblogs.com/itxdm/p/5544269.html

 关于guest-dkms和host-dkms你知道有什么区别嘛？这俩个并不是让你随便选择的，我在一篇文章上看到这俩者的区别。

     virtualbox-host-dkms是对archlinux来说的。arch是vbox主人，所以arch应该安装host-dkms。
     virtualbox-guest-dkms是对virtualbox来说的。arch是vbox客人，所以virtualbox安装arch的！

 对我来说，archlinux是我的主系统，virtualbox是我的虚拟机。（关于DKMS点这里）

     我需要真机安装virtualbox-host-dkms，然后安装virtualbox-guest-dkms是虚拟机增强工具。

 virtualbox-guest-utils是属于virtualbox中的ArchLinux安装增强工具来使用的！！！

** Virtualbox same UUID as an existing virtual machine
https://www.cscoder.cn/article/virtualbox-same-uuid-error.html

#+begin_example

VBoxManage internalcommands sethduuid   <filepath> [uuid]

需要运行两次

第一次返回一个uuid,
VBoxManage internalcommands sethduuid   <filepath> 

第二次指定UUID
VBoxManage internalcommands sethduuid   <filepath> [uuid]

#+end_example



** 设置远程vnc，密码

#+BEGIN_EXAMPLE
pacman -S  virtualbox-ext-vnc
#+END_EXAMPLE

port:3389

#+BEGIN_EXAMPLE

VBoxManage modifyvm "VM name" --vrdeproperty VNCPassword=psw

#+END_EXAMPLE

** 操作

Say we want to run the "Ubuntu Server" VM as a headless instance. To do this, you would issue the command:

#+BEGIN_SRC 
VBoxManage startvm "win7" --type headless
VBoxManage controlvm "win7" savestate --type headless
#+END_SRC

The VM will start up and hand you back your bash prompt. Your virtual server (if that's how you're using the VM) is now available to you.

If you need to pause that VM, issue the command:

#+BEGIN_SRC 
VBoxManage controlvm "Ubuntu Server" pause --type headless
#+END_SRC


To restart that paused VM, issue the command:

#+BEGIN_SRC 
VBoxManage controlvm "Ubuntu Server" resume --type headless
#+END_SRC

To shut down the VM, issue the command:

#+BEGIN_SRC 
VBoxManage controlvm "Ubuntu Server" poweroff --type headless
#+END_SRC

** wake on lan
https://wiki.archlinux.org/index.php/Wake-on-LAN


motherboard and Network Interface Controller have to support Wake-on-LAN.

#+BEGIN_EXAMPLE

cat /proc/acpi/wakeup
#+END_EXAMPLE


192.168.62.26 maca

#+BEGIN_EXAMPLE
 a4:1f:72:59:d1:84 

#+END_EXAMPLE


* xdg-utils
 Command line tools that assist applications with a variety of desktop integration tasks
** xdg-mime
* 设置鼠标速度
  https://wiki.archlinux.org/index.php/Libinput

http://rocksaying.tw/archives/48245554.html

#+begin_verse
xinput list
xinput list-props device
xinput set-prop device option-number setting
xinput get-button-map 

#+end_verse

#+BEGIN_EXAMPLE
xinput --set-prop $trackball_id 'libinput Accel Speed' 1 # 设置 mouse 速度 (-1.0 ~1.0)
#+END_EXAMPLE


* 一行命令解决linux显示txt乱码
一行命令解决linux显示windows中文txt乱码的问题
前提是你的linux可以正常显示中文，只是打开windows txt文件会有乱码。
原因是linux下用的编码一般是utf-8； windows 一般是gb18030或gb2312；那么只需要简单的转换下就可以正常显示了。
用以下命令：(需要首先安装convert转换器：#yum install convert)
# iconv -f gb18030 -t utf-8 test.txt > test utf8.txt
（-f 就是源编码from，-t 转换目标编码to，test.txt是源文件，>是重定向，testutf8.txt是生成目标编码的文件）。
注：上一行所用命令中到gb18030也可以用gb2312代替，GB18030编码向下兼容GBK和GB2312，兼容的含义是不仅字符兼容，而且相同字符的编码也相同。推荐优先使用gb18030.
* 'rxvt-unicode-256color': unknown terminal type.
    /etc/profile 加入
#+BEGIN_EXAMPLE
  export TERM="xterm"
#+END_EXAMPLE



* 解决sudo: sorry, you must have a tty to run sudo



1. 编辑 /etc/sudoers
 
  1）Defaults    requiretty，修改为 #Defaults    requiretty，表示不需要控制终端。
 
  2）Defaults    requiretty，修改为 Defaults:nobody !requiretty，表示仅 nobody 用户不需要控制终端。

  如果修改为 Defaults:%nobody !requiretty，表示仅 nobody 组不需要控制终端。
 
其实只要注释掉）Defaults    requiretty 那个就可以了。表示在执行的时候不打开终端。但是，有的shell必须要有终端才可以执行。这样显然是不行的。后来，又找到一片文章才搞定。下面为抄录的，仅为记录以后使用。
 

* rename    

** per-rename

http://www.cnblogs.com/hester/p/5615871.html

nam perl-rename

#+BEGIN_EXAMPLE

还有几个好玩的例子：
比如统一在文件头部添加上hello 
rename         's/^/hello/'       *
统一把.html扩展名修改为.htm
rename          's/.html$/.htm/'      *
统一在尾部追加.zip后缀：
rename          's/$/.zip/'      *
统一去掉.zip后缀：
 
rename          's/.zip$//'      *
 
规则化数字编号名，比如1.jpg, 2.jpg ..... 100.jpg , 现在要使文件名全部三位即1.jpg .... 001.jpg
 
运行两次命令：
 
rename           's/^/00/'          [0-9].jpg     # 这一步把1.jpg ..... 9.jpg 变幻为001.jpg .... 009.jpg
 
rename            's/^/0/'           [0-9][0-9].jpg   # 这一步把10.jpg ..... 99.jpg 变幻为010.jpg ..... 090.jpg

#+END_EXAMPLE


* 安装macos on virtualbox

https://www.tactig.com/how-to-install-macos-high-sierra-10-13-on-virtualbox/
修改虚拟机文件

#+BEGIN_SRC bash

VBoxManage modifyvm "macos" --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff
VBoxManage setextradata "macos" "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct" "iMac11,3"
VBoxManage setextradata "macos" "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion" "1.0"
VBoxManage setextradata "macos" "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct" "Iloveapple"
VBoxManage setextradata "macos" "VBoxInternal/Devices/smc/0/Config/DeviceKey" "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
VBoxManage setextradata "macos" "VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC" 1



#+END_SRC

** 分辨率
#+BEGIN_SRC 

VBoxManage setextradata "macos" "VBoxInternal2/EfiGraphicsResolution" "1600x900"

#+END_SRC
* macos上的xev软件
  - keycodes
  
* linux 访问iphone

#+BEGIN_VERSE

准备工作

1.在iphone弹出信任窗口一定要信任;


 idevicepair pair

2.安装ifuse

sudo apt-get install ifuse

3.创建一个挂载点(随便创建，我在/media目录下创建了ｕ目录)

sudo mkdir /media/u

4.使用ifuse挂载

ifuse /media/u

此时提示如下:

fusermount: failed to open /etc/fuse.conf: Permission denied
fusermount: user has no write access to mountpoint /media/u
解决方案:

sudo chmod 777 /media/u

再试着挂载:

ifuse /media/u


#+END_VERSE

fusermount -u /media/iPhone/ 


http://www.cnblogs.com/dakewei/p/6849073.html
https://www.dedoimedo.com/computers/linux-iphone-6.html

* iphone org-mode

http://lists.gnu.org/r/emacs-orgmode/2009-03/msg00690.html

#+BEGIN_VERSE  markdown

Table of Contents
=================
1 Basic principles
   1.1 Simplicity
   1.2 Forget Synchronization
   1.3 Offline
2 Main features
   2.1 Capture
   2.2 Display of current tasks
   2.3 Flagging
3 Implementation proposal
   3.1 Main screen
   3.2 Data Desktop->iPod
   3.3 Data iPhone->Desktop
4 The experience on the Emacs side


1 Basic principles
~~~~~~~~~~~~~~~~~~~

1.1 Simplicity
===============
  Don't even think about re-creating Org-mode for the
  iPhone/iPod.  If this is what you want, get a mobile
  device that runs Emacs.

  Too many companies have tried to duplicate their desktop
  experience on the iPhone, and most have, in my opinion
  failed.  If you look at the iPhone versions of Things,
  OmniFocus, Evernote, you name it, all of them are too
  complicated for the touch interface.  Simplicity is the
  absolute key to make things work on that platform.  When
  I am trying to enter a new note in Evernote, for example,
  it drives me crazy that I have to tap on the title
  filed, just to start entering a title, then tap done,
  then tap a date field, use some unpleasant interface to
  select a date, then tap done, all of this before I have
  even started to write my note.

  Apples Notes app does that right, tap "+" to create a
  note, and then type away, title automatically extracted
  from the first line, done.

1.2 Forget Synchronization
===========================
  I believe that something that does direct, 2-way
  synchronization between Org and a mobile app will be very
  hard to get right.  Instead, I propose a two data
  streams, one from the desktop to the app, one back.

1.3 Offline
============
  I believe it is essential that this app works offline as
  well.  You could be on a plane, or, more importantly, you
  could be an iPod Touch user (I am), unwilling to pay $30
  or more per month to keep your data service running.

  I am an offline user.  I downloaded most of Wikipedia
  onto the Touch, and being able to use the app offline I
  see as an essential feature.

2 Main features
~~~~~~~~~~~~~~~~

2.1 Capture
============
  Create new Org entries like notes in as primitive a way
  as possible.

2.2 Display of current tasks
=============================
  List the most recent agenda view from the desktop,
  including the task list and whatever other views you have
  configured for this.  Just one simple list to rule them
  all, maybe with toolbar buttons to jump to the agenda
  section, the task list section, etc.  Simplicity!

2.3 Flagging
=============
  In the list of tasks, have at most two buttons for each
  task.  Actually I would be satisfied only the first
  one, but might like the second one.  Here are the buttons:

  1. Flag entry for later attention when I am back at my
     desktop
  2. Done, get it out of my sight without further
     interaction.  Precise action to be defined in Emacs.


3 Implementation proposal
~~~~~~~~~~~~~~~~~~~~~~~~~~

3.1 Main screen
================
  Directly into the task list, with a top level button to
  create a new task/note, maybe in the tool bar at the
  bottom of the page.

3.2 Data Desktop->iPod
=======================
  Make Emacs automatically create a special agenda-like
  view, containing the agenda for the coming week, and
  current task.  We can configure this in Emacs, and I can
  push out this list in any desired format.  Each entry
  listed will be forced to have an ID, for unique
  identification.

  I don't know how to get this list onto the iPhone, maybe
  the easiest would be to mount the iPhone via WiFi and to
  push a single file onto it.  Apps like Datacase do this
  kind of a thing.

3.3 Data iPhone->Desktop
=========================
  The iPhone app should create a single file like an RSS
  feed.  This feed would contain two kinds of items
  1. New entries captured.  We could be really clever on
     the Desktop/Emacs side in parsing these new entries,
     extracting free form dates from things like +2Fri
     etc.  Now stupid date input forms on the iPhone, just
     free typing and clever interpretation.
  2. IDs of flagged entries.  The next time at your
     Desktop, Emacs will make an agenda view listing all
     the flagged entries, and then you can archive them,
     add notes, changes states, from you memory.  You will
     do this in the full environment provided by Emacs, not
     on a crippled interface.  In this way, the lack of
     synchronization will be a feature, not a bug.

4 The experience on the Emacs side
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1. When you start Org-mode, we would check if the iPhone is
    mounted.  If yes, we would periodically (with a timer)
    create the latest best agenda view and push it onto the
    device, so that you have a fresh version when you
    disconnect.
 2. If the phone is mounted, Emacs would check if the
    "feed" file exists.  If yes, it would read it and
    remove it from the iPhone so that new entries will
    create a new feed file.  Emacs would add the new node
    to an inbox (like org-feed.el does now for RSS feeds).
    It would mark and archive (or whatever you configure
    for this) the entries flagged as "get out of my
    sight".  And it would store the list of IDs of entries
    that require "attention", and will offer agenda views
    based on this list.

This is it.  This would make me happy.  I would of course
be willing to handle the entire Emacs side of this.

Comments?

#+END_VERSE

* create_ap

https://wiki.archlinux.org/index.php/Software_access_point_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)
https://github.com/oblique/create_ap
** 解决create_ap ERROR: Failed to initialize lock

#+begin_src bash  

rm /tmp/create_ap.all.lock
#+end_src


Note: 如果你有一个基于RTL8192CU芯片组的网卡, 请从AUR中安装hostapd-rtl871xdrvAUR并在hostapd.conf 文件中将driver=nl80211 换成 driver=rtl871xdrv。

* bluetooth-蓝牙 (air pods)

** install bluez
sudo pacman -S bluez bluez-utils blueman     

sudo systemctl start bluetooth.service

** configure file
 https://raymondjdouglas.com/blog/2019/airpods-on-arch/

sudo vi /etc/bluetooth/main.conf


ControllerMode = bredr

sudo systemctl restart bluetooth

** install pulseaudio

pacman -S pulseaudio-bluetooth pulseaudio-alsa
pulseaudio --start

* manage dotfile using "stow"

  https://farseerfc.me/zhs/using-gnu-stow-to-manage-your-dotfiles.html
* ssh 不输入密码

在自己的机器
#+BEGIN_EXAMPLE
ssh-keygen -t rsa
#+END_EXAMPLE

接受默认值就行

其中公共密钥保存在 ~/.ssh/id_rsa.pub
私有密钥保存在 ~/.ssh/id_rsa

scp id_rsa.pub到服务器的用户目录下

#+BEGIN_EXAMPLE
 scp ~/.ssh/id_rsa.pub rh1:/home/user1/.ssh/authorized_keys
#+END_EXAMPLE

** http://bbs.chinaunix.net/thread-343905-1-1.html

有些时候，我们在复制/移动文件到另一台机器时会用到scp，因为它比较安全。但如果每次

都要输入密码，就比较烦了，尤其是在script里。不过，ssh有另一种用密钥对来验证的方

式。下面写出我生成密匙对的过程，供大家参考。

第一步：生成密匙对，我用的是rsa的密钥。使用命令 "ssh-keygen -t rsa"


       [user1@rh user1]$ ssh-keygen -t rsa
       Generating public/private rsa key pair.
       Enter file in which to save the key (/home/user1/.ssh/id_rsa):
       Created directory '/home/user1/.ssh'.
       Enter passphrase (empty for no passphrase):
       Enter same passphrase again:
       Your identification has been saved in /home/user1/.ssh/id_rsa.
       Your public key has been saved in /home/user1/.ssh/id_rsa.pub.
       The key fingerprint is:
       e0:f0:3b:d3:0a:3d:da:42:01:6a:61:2f:6c:a0:c6:e7 user1@rh.test.com
       [user1@rh user1]$

复制代码

生成的过程中提示输入密钥对保存位置，直接回车，接受默认值就行了。接着会提示输入一

个不同于你的password的密码，直接回车，让它空着。当然，也可以输入一个。(我比较懒

，不想每次都要输入密码。) 这样，密钥对就生成完了。

其中公共密钥保存在 ~/.ssh/id_rsa.pub
私有密钥保存在 ~/.ssh/id_rsa

然后改一下 .ssh 目录的权限，使用命令 "chmod 755 ~/.ssh"


       [user1@rh user1]$ chmod 755 ~/.ssh
       [user1@rh user1]$

复制代码


之后把这个密钥对中的公共密钥复制到你要访问的机器上去，并保存为

~/.ssh/authorized_keys.


       [user1@rh user1]$ scp ~/.ssh/id_rsa.pub rh1:/home/user1/.ssh/authorized_keys
       user1@rh1's password:
       id_rsa.pub                                    100%  228     3.2MB/s   00:00
       [user1@rh user1]$

复制代码


之这样就大功告成了。之后你再用ssh scp sftp 之类的访问那台机器时，就不用输入密码

了，用在script上更是方便。

** 
 http://jingyan.baidu.com/article/f3ad7d0fe7bd0d09c2345b75.html
 - 首先登入一台linux服务器，此台做为母机（即登入其他linux系统用这台做为入口）；执行一行命令生成key文件：

#+BEGIN_EXAMPLE
ssh-keygen -t rsa
#+END_EXAMPLE
  - 在母机上，进入/roo/.ssh目录，找到id_rsa.pub该文件，这个文件就是刚才执行ssh-keygen所生成的公钥key文件。

  - 用scp命令，将母机产生的key拷一份到远程的linux服务器上，并命名成authorized_keys；scp ~/.ssh/id_rsa.pub  root@192.168.1.113:/root/.ssh/authorized_keys。这一步的操作需要手动输入密码。
如何通过linux ssh远程linux不用输入密码登入
  - 现在为止，你已完成了所有的操作；可在母机通过ssh root@192.168.1.113 你会发现不在用输放密码了。相同的scp命令也是一样的情况，无需手动输入密码

  注意: 要正确命名公钥的名称

* libreoffice 转换文件格式(doc, pdf...) 代替(pandoc的相同格式转换)



#+BEGIN_SRC 
libreoffice --invisible --convert-to docx test.odt

#+END_SRC



* su: Authentication failure
I fixed the UID with Konqueror <Properties>. For my information, how do you add UID with "chown"?

You mean chmod?  chmod u+s <file>


>>> The module r8168 conflicts with r8169. You can blacklist it with:
>>>  `echo "blacklist r8169" > /etc/modprobe.d/r8169_blacklist.conf`
ldconfig: /usr/lib/libjlinkarm.so.4 is not a symbolic link
* OCR
https://help.ubuntu.com/community/OCR

#+BEGIN_SRC 
    fuzzyocr - spamassassin plugin to check image attachments

    gocr - a command line OCR

    libhocr0 - Hebrew OCR

    ocrad - OCR program

    ocrfeeder - document layout analysis and optical character recognition system

    ocropus - document analysis and OCR system

    tesseract-ocr - command line OCR 

The Ubuntu multiverse respositories also contain:

    cuneiform - multi-language OCR system 

#+END_SRC
** tesseract
  - gimagereader
  - tesseract-data-chi_sim
  - tesseract-data-chi_tra
  -  hunspell-<lang>

* boogie board
** python 
https://github.com/jbedo/boogiesync-tablet

pip install pyusb

** c

https://github.com/chonan/boogie
  

* xorg evdev vs. libinput

* bash 文件大小
#+BEGIN_EXAMPLE


ls -l filename | awk '{print $5}'

du -b filename | awk '{print $1}'

wc -c filename | awk '{print $1}'

wc -c < filename

stat -c "%s" filename

#+END_EXAMPLE
* wine: emulate a virtual desktop

#+BEGIN_SRC 

  pacman -S winetricks
  WINEARCH=win32 winetricks qq 

#+END_SRC
** wine in Xmonad is not tiling
http://unix.stackexchange.com/questions/71318/wine-in-xmonad-is-not-tiling


Q: I'm using Wine application in Xmonad. But it is not tiling like other applications. Can this be configured, that Wine will tile like other applications?

A: You're not giving me a whole lot to work with (no details about your wine setup) but maybe the following will help: Run winecfg, switch to the graphics tab and tell it to emulate a virtual desktop (choose an appropriate size). Afterwards, everything should tile nicely.
A: Wine programs default to floating, but using super-t (or whatever key binding you use for turning on tiling) will make them tile just fine. Is that your issue?



* 自动备份

#+begin_src bash  
#!/bin/sh
BACKUPDIR=/home/BACKUP
LOGFILE=/home/data/backup.log
DIRFILE=/home/data/dir_need_backup
SUBDIR=`cat$DIRFILE`
MAILTO="zzz@163.com bbb@163.com"
BACKUP=$BACKUPDIR/backup
BACKUP_TMP=$BACKUPDIR/backup_tmp
#checkdirs
if [! -d $BACKUP ]; then
  mkdir-p $BACKUP
fi
if [! -d $BACKUP_TMP ]; then
  mkdir-p $BACKUP_TMP
fi
echo"Start backup!!!" > $LOGFILE 2>&1
fori in $SUBDIR
do
  echo$i >> $LOGFILE 2>&1
  if[ -f $i/HEAD ]; then
    #cleanup the git repository
    cd $i
    sudo su git -c "git gc" >> $LOGFILE 2>&1
    cd -
    #backup start
    mkdir$BACKUP_TMP/`basename $i`
    gitclone --bare $i $BACKUP_TMP/`basename $i` >> $LOGFILE 2>&1
    if[ $? = 0 ]; then
      echo$i backup success!!! >> $LOGFILE 2>&1
      rm-rf $BACKUP/`basename $i`
      mv$BACKUP_TMP/`basename $i` $BACKUP
    else
      echo$i backup fail!!! >> $LOGFILE 2>&1
      echo"Error occured during backup $i, detail in $LOGFILE" |mutt -s "BACKUP MESSAGE" $MAILTO
    fi
  else
    echo$i is not a git dir!!! >> $LOGFILE 2>&1
  fi
done
echo"Backup complete!!!" >> $LOGFILE 2>&1
#+end_src


* rrdtool
  Data logging and graphing application


  
* icloud / nativefier

npm i -g nativefier

nativefier -p linux -a x64 -i icon.png --disable-context-menu --disable-dev-tools --single-instance https://www.icloud.com/
