* EAS/WebDav/CalDav/CardDav/WebCal/iCalendar
WebDAV （Web-based Distributed Authoring and Versioning）
https://blog.csdn.net/qq_36731677/article/details/82956977
简单认识EAS/WebDav/CalDav/CardDav/WebCal/iCalendar的含义

前言

最近在实现一个事务同步的软件功能，但前提是尽可能的避免用户安装新的应用，也尽可能的避免使用微信小程序或让用户提供隐私数据，最最最还要注意的是跨平台的兼容性，思来想去也就是各个设备上的邮箱功能了，那个玩意的通用性是真的强。
现在大多数设备上的邮件同步系统都支持IMAP、POP3、Exchange服务，而Exchange服务可以同步日历，那么该服务是如何实现的呢？为了开发我们要进一步摸清其中的原理。
让我们先通过一个图纵观系统结构
在这里插入图片描述

#+begin_example

                         +---------------------------------------------------------------------------------------------------------------------------------+
                         |  ExchangeActiveSync                                                                                                             |
                         |    +-----------------------------------------------------------------------------------------------------------------------+    |
                         |    |                                 mail sync                                                                             |    |
                         |    +-----------------------------------------------------------------------------------------------------------------------+    |
                         |    +-----------------------------------------------------------------------------------------------------------------------+    |
                         |    |  WebDav https://xxx.xxx/...                                                                                           |    |
                         |    |   +--------------------------------------------------------------------------------+       +---------------------+    |    |
                         |    |   | WebCal webcal://xxx.xxx/...                                                    |       |                     |    |    |
                         |    |   |                                                                                |       |     other           |    |    |
                         |    |   |  +---------------------------+    +---------------------------+                |       |                     |    |    |
                         |    |   |  | CalDav                    |    | CardDav                   |                |       |     operation       |    |    |
                         |    |   |  |    +-----------------+    |    |   +-------------------+   |                |       |                     |    |    |
                         |    |   |  |    | iCalendar       |    |    |   |  vCard            |   |                |       |                     |    |    |
                         |    |   |  |    +-----------------+    |    |   +-------------------+   |                |       |                     |    |    |
                         |    |   |  +---------------------------+    +---------------------------+                |       |                     |    |    |
                         |    |   +--------------------------------------------------------------------------------+       +---------------------+    |    |
                         |    +-----------------------------------------------------------------------------------------------------------------------+    |
                         +---------------------------------------------------------------------------------------------------------------------------------+

#+end_example

ExchangeActiveSync协议

    标准：该协议不是国际标准，但却是事实上的协议，该协议的技术来源于微软
    功能描述：该协议可实现从服务器到客户端的电子邮件，联系人，日历，任务和便笺的同步（国内厂商大部分都只看中邮件同步的功能）
    基础协议：XML，HTTP，HTTPS
    支援软件：谷歌家Gmail、微软家Outlook、腾讯家的Foxmail等
    协议应用：可引导用户向Gmail或者Outlook中添加日程订阅，并将邮件账户通过Exchange

WebDav

    标准：RFC 4918
    功能描述：基于HTTP的数据操作协议，提供分布式创作与版本控制功能。简单来说就是允许客户端发布、锁定和管理服务器中的部分资源，而且该操作可以是有权限的、多用户的。
    基础协议：基于HTTP1.1的扩展
    支援软件： Dropbox、坚果云、OwnCloud等服务
    协议应用：该协议常见于网盘系统（服务器）并被常见的操作系统所支持（客户端），允许用户将云盘以网络驱动器的形式挂载到客户端系统上，可自由的上传、修改和下载文件资源。该协议是CalDav协议的基础。

WebCal

    标准：该协议不是国际标准，但却是事实上的标准
    功能描述：用于访问iCalendar文件的非官方统一资源标识符（URI）方案。简单来说就是一种自定义的URL标识，但是该标识被不少软件所认可，通过该协议可以访问服务器上的日程资源，也就是访问iCalendar文件。
    基础协议：未知
    支援软件：Google Calendar、Microsoft Outlook、Mozilla Lightning
    协议应用：该标准最早被设计用于苹果的iCal应用程序，应用程序发起的请求以webcal://为开头，被服务器上的外部协议处理程序所捕获，并通过WebDav协议操作iCalendar文件。这种非国际标准的请求可能会被不兼容的应用程序拦截并认定为下载iCalendar文件（后缀为.ics）。所以综合来说，基本上可以认为下载*.ics文件并导入应用程序和直接使用链接webcal://xxx.xxx.xxx/....导入的是相同的行为。

CalDav

    标准：RFC 4791
    功能描述：远程日程信息访问（共享）协议。允许客户端访问共享服务器上的日程信息。简单来说就是允许具有权限的用户访问一份共享的日程。
    基础协议：扩展了WebDav协议的规范， 并使用iCalendar格式的数据
    支援软件：CalDav服务器与操作系统（国内安卓基本都不支持）
    协议应用：该协议被各大邮件系统所支持，利用该协议可引导用户订阅日程信息流，并将日程信息通过邮箱帐号同步至绑定的设备中。但是，国内的邮件系统基本不支持日程的订阅服务属于阉割版本，应有条件的采用国际大厂的日程订阅服务。这种日程订阅的方案虽然没有即时通讯那么快，但是和邮件的同步速度旗鼓相当。

CardDav

    标准：RFC 6352
    功能描述：远程地址簿信息访问（共享）协议。允许客户端访问共享服务器上的联系人数据。简单来说就是允许具有权限的用户访问一份共享的地址簿。
    基础协议：扩展了WebDav协议的规范， 并使用vCard格式的数据
    支援软件：Apple Contacts、Outlook CalDav Synchronizer、GMail
    协议应用：该协议可认为是CalDav协议的孪生兄弟，一般支持CalDav同步的邮箱系统都可以支持CardDav的同步。

iCalendar

    标准： RFC 5545
    功能描述：日程信息文件交换格式。允许用户通过各种方法共享或发送此格式的文件，将会议请求和任务发送给其他用户。简单来说就是规范的将"时间、地点、人物"等日程中的要素写入文件中，方便多用户之间的信息传输。
    基础协议：媒体类型应为text/calendar，扩展名为*.ics
    支援软件：好多好多，但是兼容性各有千秋
    协议应用：可以引导用户下载ics文件并导入在邮件系统的日程订阅中已完成日程信息的数据同步，不过能用webcal链接时还是链接更妙一些。建议使用时多关注一下文件协议的格式版本，部分不兼容的版本可能会被订阅程序所拒绝。

以上内容都是我个人对于协议的理解与认知，部分信息来源于维基百科，如果有什么错误欢迎指正。



* kernal module load
** virtualbox
/etc/modules-load.d/virtualbox.conf

#+BEGIN_EXAMPLE

vboxdrv
vboxguest
vboxsf
vboxvideo
vboxnetadp
vboxnetflt


#+END_EXAMPLE


** 
#+BEGIN_EXAMPLE
man modules-load.d
#+END_EXAMPLE

  modules-load.d

 systemd-modules-load.service(8) reads files from the above
       directories which contain kernel modules to load during boot in a
       static list. Each configuration file is named in the style of
       /etc/modules-load.d/program.conf. Note that it is usually a better
       idea to rely on the automatic module loading by PCI IDs, USB IDs, DMI
       IDs or similar triggers encoded in the kernel modules themselves
       instead of static configuration like this. In fact, most modern
       kernel modules are prepared for automatic loading already.
https://wiki.archlinux.org/index.php/Systemd

Troubleshooting

#+BEGIN_EXAMPLE
$ systemctl --failed
$ systemctl status systemd-modules-load
$ journalctl _PID=15630
#+END_EXAMPLE

* hhkb下　disable power键

xev
evtest 查看操作事件



https://unix.stackexchange.com/questions/106468/remapping-power-key-to-delete
** xkb
#+BEGIN_EXAMPLE
key <POWR> { [ prior] } //不管用
#+END_EXAMPLE

keycode = 124

** /etc/systemd/logind.conf

#+BEGIN_SRC 
HandlePowerKey=ignore
#+END_SRC



systemd can handle this. I think this is what you need:

Open the /etc/systemd/logind.conf (manual):

    HandlePowerKey: action on power key is pressed;
    HandleSuspendKey: action on suspend key is pressed.
    HandleHibernateKey: action on hibernate key is pressed.
    HandleLidSwitch: action when the lid is closed.

The action can be one of ignore, poweroff, reboot, halt, suspend, hibernate or kexec.

If no configuration, default values used:

    HandlePowerKey=poweroff
    HandleSuspendKey=suspend
    HandleHibernateKey=hibernate
    HandleLidSwitch=suspend



** Change Behavior of Linux Power Button

https://superuser.com/questions/699905/change-behavior-of-linux-power-button


Well, one thing you could do is simply disable the power button altogether. Personally, I only use it to turn on my machine, and never use it once the machine is on. If this is an OK solution for you, edit /etc/acpi/events/powerbtn-acpi-support:

sudo nano /etc/acpi/events/powerbtn-acpi-support

That file should look something like this:

event=button[ /]power
action=/etc/acpi/powerbtn-acpi-support.sh

To make the power button do nothing, change it to:

event=button[ /]power
action=

Then restart the acpi daemon with

sudo service acpid restart

Your power button should no be ignored.

* virtualbox
** virtual machine
 https://en.wikipedia.org/wiki/Virtual_machine


 在详细介绍之前，有几个概念要说明：
 1. VM（Virtual Machine）——虚拟机，指由Vmware模拟出来的一台虚拟的计算机，也即逻辑上的一台计算机。
 2.HOST——指物理存在的计算机，Host′s OS指HOST上运行的操作系统。
 3. Guest OS——指运行在VM上的操作系统。例如在一台安装了Windows NT的计算机上安装了Vmware，那么，HOST指的是安装Windows NT的这台计算机，其Host′s OS为Windows NT。VM上运行的是Linux，那么Linux即为Guest OS。

*** ArchLinux 下 VirtualBox 增强设置
 http://www.cnblogs.com/itxdm/p/5544269.html

 关于guest-dkms和host-dkms你知道有什么区别嘛？这俩个并不是让你随便选择的，我在一篇文章上看到这俩者的区别。

     virtualbox-host-dkms是对archlinux来说的。arch是vbox主人，所以arch应该安装host-dkms。
     virtualbox-guest-dkms是对virtualbox来说的。arch是vbox客人，所以virtualbox安装arch的！

 对我来说，archlinux是我的主系统，virtualbox是我的虚拟机。（关于DKMS点这里）

     我需要真机安装virtualbox-host-dkms，然后安装virtualbox-guest-dkms是虚拟机增强工具。

 virtualbox-guest-utils是属于virtualbox中的ArchLinux安装增强工具来使用的！！！

** Virtualbox same UUID as an existing virtual machine
https://www.cscoder.cn/article/virtualbox-same-uuid-error.html

#+begin_example

VBoxManage internalcommands sethduuid   <filepath> [uuid]

需要运行两次

第一次返回一个uuid,
VBoxManage internalcommands sethduuid   <filepath> 

第二次指定UUID
VBoxManage internalcommands sethduuid   <filepath> [uuid]

#+end_example



** 设置远程vnc，密码

#+BEGIN_EXAMPLE
pacman -S  virtualbox-ext-vnc
#+END_EXAMPLE

port:3389

#+BEGIN_EXAMPLE

VBoxManage modifyvm "VM name" --vrdeproperty VNCPassword=psw

#+END_EXAMPLE

** 操作

Say we want to run the "Ubuntu Server" VM as a headless instance. To do this, you would issue the command:

#+BEGIN_SRC 
VBoxManage startvm "win7" --type headless
VBoxManage controlvm "win7" savestate --type headless
#+END_SRC

The VM will start up and hand you back your bash prompt. Your virtual server (if that's how you're using the VM) is now available to you.

If you need to pause that VM, issue the command:

#+BEGIN_SRC 
VBoxManage controlvm "Ubuntu Server" pause --type headless
#+END_SRC


To restart that paused VM, issue the command:

#+BEGIN_SRC 
VBoxManage controlvm "Ubuntu Server" resume --type headless
#+END_SRC

To shut down the VM, issue the command:

#+BEGIN_SRC 
VBoxManage controlvm "Ubuntu Server" poweroff --type headless
#+END_SRC

** wake on lan
https://wiki.archlinux.org/index.php/Wake-on-LAN


motherboard and Network Interface Controller have to support Wake-on-LAN.

#+BEGIN_EXAMPLE

cat /proc/acpi/wakeup
#+END_EXAMPLE


192.168.62.26 maca

#+BEGIN_EXAMPLE
 a4:1f:72:59:d1:84 

#+END_EXAMPLE

** 添加摄像头
   https://blog.csdn.net/zhangrelay/article/details/100122944

   - Oracle VM VirtualBox Extension Pack
   - 启动虚拟机, 在 设备 -> 摄像头 -> 启用摄像头设备
   - $ls /dev/video*
   - cheese      测试为黑屏
   - xawtv -d /dev/video1

* 安装macos on virtualbox

https://www.tactig.com/how-to-install-macos-high-sierra-10-13-on-virtualbox/
修改虚拟机文件

#+BEGIN_SRC bash

VBoxManage modifyvm "macos" --cpuidset 00000001 000106e5 00100800 0098e3fd bfebfbff
VBoxManage setextradata "macos" "VBoxInternal/Devices/efi/0/Config/DmiSystemProduct" "iMac11,3"
VBoxManage setextradata "macos" "VBoxInternal/Devices/efi/0/Config/DmiSystemVersion" "1.0"
VBoxManage setextradata "macos" "VBoxInternal/Devices/efi/0/Config/DmiBoardProduct" "Iloveapple"
VBoxManage setextradata "macos" "VBoxInternal/Devices/smc/0/Config/DeviceKey" "ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc"
VBoxManage setextradata "macos" "VBoxInternal/Devices/smc/0/Config/GetKeyFromRealSMC" 1



#+END_SRC

** 分辨率
#+BEGIN_SRC 

VBoxManage setextradata "macos" "VBoxInternal2/EfiGraphicsResolution" "1600x900"

#+END_SRC
** 共享目录
   - mount point (auto mount)
     /media/sf_<共享目录的名字>
   - 你的用户需要加入到 vboxsf 用户组
   #+begin_example
     sudo usermod -a -G vboxsf USER
   #+end_example

     
* xdg-utils
 Command line tools that assist applications with a variety of desktop integration tasks
** xdg-mime
* 设置鼠标速度
  https://wiki.archlinux.org/index.php/Libinput

http://rocksaying.tw/archives/48245554.html

#+begin_verse
xinput list
xinput list-props device
xinput set-prop device option-number setting
xinput get-button-map 

#+end_verse

#+BEGIN_EXAMPLE
xinput --set-prop $trackball_id 'libinput Accel Speed' 1 # 设置 mouse 速度 (-1.0 ~1.0)
#+END_EXAMPLE

* 一行命令解决linux显示txt乱码
一行命令解决linux显示windows中文txt乱码的问题
前提是你的linux可以正常显示中文，只是打开windows txt文件会有乱码。
原因是linux下用的编码一般是utf-8； windows 一般是gb18030或gb2312；那么只需要简单的转换下就可以正常显示了。
用以下命令：(需要首先安装convert转换器：#yum install convert)
# iconv -f gb18030 -t utf-8 test.txt > test utf8.txt
（-f 就是源编码from，-t 转换目标编码to，test.txt是源文件，>是重定向，testutf8.txt是生成目标编码的文件）。
注：上一行所用命令中到gb18030也可以用gb2312代替，GB18030编码向下兼容GBK和GB2312，兼容的含义是不仅字符兼容，而且相同字符的编码也相同。推荐优先使用gb18030.
* 'rxvt-unicode-256color': unknown terminal type.
    /etc/profile 加入
#+BEGIN_EXAMPLE
  export TERM="xterm"
#+END_EXAMPLE



* 解决sudo: sorry, you must have a tty to run sudo



1. 编辑 /etc/sudoers
 
  1）Defaults    requiretty，修改为 #Defaults    requiretty，表示不需要控制终端。
 
  2）Defaults    requiretty，修改为 Defaults:nobody !requiretty，表示仅 nobody 用户不需要控制终端。

  如果修改为 Defaults:%nobody !requiretty，表示仅 nobody 组不需要控制终端。
 
其实只要注释掉）Defaults    requiretty 那个就可以了。表示在执行的时候不打开终端。但是，有的shell必须要有终端才可以执行。这样显然是不行的。后来，又找到一片文章才搞定。下面为抄录的，仅为记录以后使用。
 

* rename    

** per-rename

http://www.cnblogs.com/hester/p/5615871.html

nam perl-rename

#+BEGIN_EXAMPLE

还有几个好玩的例子：
比如统一在文件头部添加上hello 
rename         's/^/hello/'       *
统一把.html扩展名修改为.htm
rename          's/.html$/.htm/'      *
统一在尾部追加.zip后缀：
rename          's/$/.zip/'      *
统一去掉.zip后缀：
 
rename          's/.zip$//'      *
 
规则化数字编号名，比如1.jpg, 2.jpg ..... 100.jpg , 现在要使文件名全部三位即1.jpg .... 001.jpg
 
运行两次命令：
 
rename           's/^/00/'          [0-9].jpg     # 这一步把1.jpg ..... 9.jpg 变幻为001.jpg .... 009.jpg
 
rename            's/^/0/'           [0-9][0-9].jpg   # 这一步把10.jpg ..... 99.jpg 变幻为010.jpg ..... 090.jpg

#+END_EXAMPLE

* macos上的xev软件
  - keycodes
  
* linux 访问iphone

#+BEGIN_VERSE

准备工作

1.在iphone弹出信任窗口一定要信任;


 idevicepair pair

2.安装ifuse

sudo apt-get install ifuse

3.创建一个挂载点(随便创建，我在/media目录下创建了ｕ目录)

sudo mkdir /media/u

4.使用ifuse挂载

ifuse /media/u

此时提示如下:

fusermount: failed to open /etc/fuse.conf: Permission denied
fusermount: user has no write access to mountpoint /media/u
解决方案:

sudo chmod 777 /media/u

再试着挂载:

ifuse /media/u


#+END_VERSE

fusermount -u /media/iPhone/ 


http://www.cnblogs.com/dakewei/p/6849073.html
https://www.dedoimedo.com/computers/linux-iphone-6.html

* iphone org-mode

http://lists.gnu.org/r/emacs-orgmode/2009-03/msg00690.html

#+BEGIN_VERSE  markdown

Table of Contents
=================
1 Basic principles
   1.1 Simplicity
   1.2 Forget Synchronization
   1.3 Offline
2 Main features
   2.1 Capture
   2.2 Display of current tasks
   2.3 Flagging
3 Implementation proposal
   3.1 Main screen
   3.2 Data Desktop->iPod
   3.3 Data iPhone->Desktop
4 The experience on the Emacs side


1 Basic principles
~~~~~~~~~~~~~~~~~~~

1.1 Simplicity
===============
  Don't even think about re-creating Org-mode for the
  iPhone/iPod.  If this is what you want, get a mobile
  device that runs Emacs.

  Too many companies have tried to duplicate their desktop
  experience on the iPhone, and most have, in my opinion
  failed.  If you look at the iPhone versions of Things,
  OmniFocus, Evernote, you name it, all of them are too
  complicated for the touch interface.  Simplicity is the
  absolute key to make things work on that platform.  When
  I am trying to enter a new note in Evernote, for example,
  it drives me crazy that I have to tap on the title
  filed, just to start entering a title, then tap done,
  then tap a date field, use some unpleasant interface to
  select a date, then tap done, all of this before I have
  even started to write my note.

  Apples Notes app does that right, tap "+" to create a
  note, and then type away, title automatically extracted
  from the first line, done.

1.2 Forget Synchronization
===========================
  I believe that something that does direct, 2-way
  synchronization between Org and a mobile app will be very
  hard to get right.  Instead, I propose a two data
  streams, one from the desktop to the app, one back.

1.3 Offline
============
  I believe it is essential that this app works offline as
  well.  You could be on a plane, or, more importantly, you
  could be an iPod Touch user (I am), unwilling to pay $30
  or more per month to keep your data service running.

  I am an offline user.  I downloaded most of Wikipedia
  onto the Touch, and being able to use the app offline I
  see as an essential feature.

2 Main features
~~~~~~~~~~~~~~~~

2.1 Capture
============
  Create new Org entries like notes in as primitive a way
  as possible.

2.2 Display of current tasks
=============================
  List the most recent agenda view from the desktop,
  including the task list and whatever other views you have
  configured for this.  Just one simple list to rule them
  all, maybe with toolbar buttons to jump to the agenda
  section, the task list section, etc.  Simplicity!

2.3 Flagging
=============
  In the list of tasks, have at most two buttons for each
  task.  Actually I would be satisfied only the first
  one, but might like the second one.  Here are the buttons:

  1. Flag entry for later attention when I am back at my
     desktop
  2. Done, get it out of my sight without further
     interaction.  Precise action to be defined in Emacs.


3 Implementation proposal
~~~~~~~~~~~~~~~~~~~~~~~~~~

3.1 Main screen
================
  Directly into the task list, with a top level button to
  create a new task/note, maybe in the tool bar at the
  bottom of the page.

3.2 Data Desktop->iPod
=======================
  Make Emacs automatically create a special agenda-like
  view, containing the agenda for the coming week, and
  current task.  We can configure this in Emacs, and I can
  push out this list in any desired format.  Each entry
  listed will be forced to have an ID, for unique
  identification.

  I don't know how to get this list onto the iPhone, maybe
  the easiest would be to mount the iPhone via WiFi and to
  push a single file onto it.  Apps like Datacase do this
  kind of a thing.

3.3 Data iPhone->Desktop
=========================
  The iPhone app should create a single file like an RSS
  feed.  This feed would contain two kinds of items
  1. New entries captured.  We could be really clever on
     the Desktop/Emacs side in parsing these new entries,
     extracting free form dates from things like +2Fri
     etc.  Now stupid date input forms on the iPhone, just
     free typing and clever interpretation.
  2. IDs of flagged entries.  The next time at your
     Desktop, Emacs will make an agenda view listing all
     the flagged entries, and then you can archive them,
     add notes, changes states, from you memory.  You will
     do this in the full environment provided by Emacs, not
     on a crippled interface.  In this way, the lack of
     synchronization will be a feature, not a bug.

4 The experience on the Emacs side
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1. When you start Org-mode, we would check if the iPhone is
    mounted.  If yes, we would periodically (with a timer)
    create the latest best agenda view and push it onto the
    device, so that you have a fresh version when you
    disconnect.
 2. If the phone is mounted, Emacs would check if the
    "feed" file exists.  If yes, it would read it and
    remove it from the iPhone so that new entries will
    create a new feed file.  Emacs would add the new node
    to an inbox (like org-feed.el does now for RSS feeds).
    It would mark and archive (or whatever you configure
    for this) the entries flagged as "get out of my
    sight".  And it would store the list of IDs of entries
    that require "attention", and will offer agenda views
    based on this list.

This is it.  This would make me happy.  I would of course
be willing to handle the entire Emacs side of this.

Comments?

#+END_VERSE

* create_ap

https://wiki.archlinux.org/index.php/Software_access_point_(%E7%AE%80%E4%BD%93%E4%B8%AD%E6%96%87)
https://github.com/oblique/create_ap
** 解决create_ap ERROR: Failed to initialize lock

#+begin_src bash  

rm /tmp/create_ap.all.lock
#+end_src


Note: 如果你有一个基于RTL8192CU芯片组的网卡, 请从AUR中安装hostapd-rtl871xdrvAUR并在hostapd.conf 文件中将driver=nl80211 换成 driver=rtl871xdrv。

* bluetooth-蓝牙 (air pods)

** install bluez
sudo pacman -S bluez bluez-utils blueman     

sudo systemctl start bluetooth.service

** configure file
 https://raymondjdouglas.com/blog/2019/airpods-on-arch/

sudo vi /etc/bluetooth/main.conf


ControllerMode = bredr

sudo systemctl restart bluetooth

** install pulseaudio

pacman -S pulseaudio-bluetooth pulseaudio-alsa
pulseaudio --start

* manage dotfile using "stow"

  https://farseerfc.me/zhs/using-gnu-stow-to-manage-your-dotfiles.html
* ssh 不输入密码

在自己的机器
#+BEGIN_EXAMPLE
ssh-keygen -t rsa
#+END_EXAMPLE

接受默认值就行

其中公共密钥保存在 ~/.ssh/id_rsa.pub
私有密钥保存在 ~/.ssh/id_rsa

scp id_rsa.pub到服务器的用户目录下

#+BEGIN_EXAMPLE
 scp ~/.ssh/id_rsa.pub rh1:/home/user1/.ssh/authorized_keys
#+END_EXAMPLE

** http://bbs.chinaunix.net/thread-343905-1-1.html

有些时候，我们在复制/移动文件到另一台机器时会用到scp，因为它比较安全。但如果每次

都要输入密码，就比较烦了，尤其是在script里。不过，ssh有另一种用密钥对来验证的方

式。下面写出我生成密匙对的过程，供大家参考。

第一步：生成密匙对，我用的是rsa的密钥。使用命令 "ssh-keygen -t rsa"


       [user1@rh user1]$ ssh-keygen -t rsa
       Generating public/private rsa key pair.
       Enter file in which to save the key (/home/user1/.ssh/id_rsa):
       Created directory '/home/user1/.ssh'.
       Enter passphrase (empty for no passphrase):
       Enter same passphrase again:
       Your identification has been saved in /home/user1/.ssh/id_rsa.
       Your public key has been saved in /home/user1/.ssh/id_rsa.pub.
       The key fingerprint is:
       e0:f0:3b:d3:0a:3d:da:42:01:6a:61:2f:6c:a0:c6:e7 user1@rh.test.com
       [user1@rh user1]$

复制代码

生成的过程中提示输入密钥对保存位置，直接回车，接受默认值就行了。接着会提示输入一

个不同于你的password的密码，直接回车，让它空着。当然，也可以输入一个。(我比较懒

，不想每次都要输入密码。) 这样，密钥对就生成完了。

其中公共密钥保存在 ~/.ssh/id_rsa.pub
私有密钥保存在 ~/.ssh/id_rsa

然后改一下 .ssh 目录的权限，使用命令 "chmod 755 ~/.ssh"


       [user1@rh user1]$ chmod 755 ~/.ssh
       [user1@rh user1]$

复制代码


之后把这个密钥对中的公共密钥复制到你要访问的机器上去，并保存为

~/.ssh/authorized_keys.


       [user1@rh user1]$ scp ~/.ssh/id_rsa.pub rh1:/home/user1/.ssh/authorized_keys
       user1@rh1's password:
       id_rsa.pub                                    100%  228     3.2MB/s   00:00
       [user1@rh user1]$

复制代码


之这样就大功告成了。之后你再用ssh scp sftp 之类的访问那台机器时，就不用输入密码

了，用在script上更是方便。

** 
 http://jingyan.baidu.com/article/f3ad7d0fe7bd0d09c2345b75.html
 - 首先登入一台linux服务器，此台做为母机（即登入其他linux系统用这台做为入口）；执行一行命令生成key文件：

#+BEGIN_EXAMPLE
ssh-keygen -t rsa
#+END_EXAMPLE
  - 在母机上，进入/roo/.ssh目录，找到id_rsa.pub该文件，这个文件就是刚才执行ssh-keygen所生成的公钥key文件。

  - 用scp命令，将母机产生的key拷一份到远程的linux服务器上，并命名成authorized_keys；scp ~/.ssh/id_rsa.pub  root@192.168.1.113:/root/.ssh/authorized_keys。这一步的操作需要手动输入密码。
如何通过linux ssh远程linux不用输入密码登入
  - 现在为止，你已完成了所有的操作；可在母机通过ssh root@192.168.1.113 你会发现不在用输放密码了。相同的scp命令也是一样的情况，无需手动输入密码

  注意: 要正确命名公钥的名称

* libreoffice 转换文件格式(doc, pdf...) 代替(pandoc的相同格式转换)



#+BEGIN_SRC 
libreoffice --invisible --convert-to docx test.odt

#+END_SRC



* su: Authentication failure
I fixed the UID with Konqueror <Properties>. For my information, how do you add UID with "chown"?

You mean chmod?  chmod u+s <file>


>>> The module r8168 conflicts with r8169. You can blacklist it with:
>>>  `echo "blacklist r8169" > /etc/modprobe.d/r8169_blacklist.conf`
ldconfig: /usr/lib/libjlinkarm.so.4 is not a symbolic link
* OCR
https://help.ubuntu.com/community/OCR

#+BEGIN_SRC 
    fuzzyocr - spamassassin plugin to check image attachments

    gocr - a command line OCR

    libhocr0 - Hebrew OCR

    ocrad - OCR program

    ocrfeeder - document layout analysis and optical character recognition system

    ocropus - document analysis and OCR system

    tesseract-ocr - command line OCR 

The Ubuntu multiverse respositories also contain:

    cuneiform - multi-language OCR system 

#+END_SRC
** tesseract
  - gimagereader
  - tesseract-data-chi_sim
  - tesseract-data-chi_tra
  - hunspell-<lang>

* boogie board
** python 
https://github.com/jbedo/boogiesync-tablet

pip install pyusb

** c

https://github.com/chonan/boogie
  

* xorg evdev vs. libinput

* bash 文件大小
#+BEGIN_EXAMPLE


ls -l filename | awk '{print $5}'

du -b filename | awk '{print $1}'

wc -c filename | awk '{print $1}'

wc -c < filename

stat -c "%s" filename

#+END_EXAMPLE
* wine: emulate a virtual desktop

#+BEGIN_SRC 

  pacman -S winetricks
  WINEARCH=win32 winetricks qq 

#+END_SRC
** wine in Xmonad is not tiling
http://unix.stackexchange.com/questions/71318/wine-in-xmonad-is-not-tiling


Q: I'm using Wine application in Xmonad. But it is not tiling like other applications. Can this be configured, that Wine will tile like other applications?

A: You're not giving me a whole lot to work with (no details about your wine setup) but maybe the following will help: Run winecfg, switch to the graphics tab and tell it to emulate a virtual desktop (choose an appropriate size). Afterwards, everything should tile nicely.
A: Wine programs default to floating, but using super-t (or whatever key binding you use for turning on tiling) will make them tile just fine. Is that your issue?



* 自动备份

#+begin_src bash  
#!/bin/sh
BACKUPDIR=/home/BACKUP
LOGFILE=/home/data/backup.log
DIRFILE=/home/data/dir_need_backup
SUBDIR=`cat$DIRFILE`
MAILTO="zzz@163.com bbb@163.com"
BACKUP=$BACKUPDIR/backup
BACKUP_TMP=$BACKUPDIR/backup_tmp
#checkdirs
if [! -d $BACKUP ]; then
  mkdir-p $BACKUP
fi
if [! -d $BACKUP_TMP ]; then
  mkdir-p $BACKUP_TMP
fi
echo"Start backup!!!" > $LOGFILE 2>&1
fori in $SUBDIR
do
  echo$i >> $LOGFILE 2>&1
  if[ -f $i/HEAD ]; then
    #cleanup the git repository
    cd $i
    sudo su git -c "git gc" >> $LOGFILE 2>&1
    cd -
    #backup start
    mkdir$BACKUP_TMP/`basename $i`
    gitclone --bare $i $BACKUP_TMP/`basename $i` >> $LOGFILE 2>&1
    if[ $? = 0 ]; then
      echo$i backup success!!! >> $LOGFILE 2>&1
      rm-rf $BACKUP/`basename $i`
      mv$BACKUP_TMP/`basename $i` $BACKUP
    else
      echo$i backup fail!!! >> $LOGFILE 2>&1
      echo"Error occured during backup $i, detail in $LOGFILE" |mutt -s "BACKUP MESSAGE" $MAILTO
    fi
  else
    echo$i is not a git dir!!! >> $LOGFILE 2>&1
  fi
done
echo"Backup complete!!!" >> $LOGFILE 2>&1
#+end_src


* rrdtool
  Data logging and graphing application


  
* icloud / nativefier

npm i -g nativefier

nativefier -p linux -a x64 -i icon.png --disable-context-menu --disable-dev-tools --single-instance https://www.icloud.com/
* xdm (IDM on linux)
update the links: 
#+begin_example

ln -sf /usr/bin/youtube-dl /opt/xdman/youtube-dl
ln -sf /usr/bin/ffmpeg /opt/xdman/ffmpeg

#+end_example
* caldav (icloud)

https://unoun.github.io/2016/06/how-to-get-icloud-caldav-and-carddav-url/
https://askubuntu.com/questions/911567/how-to-sync-icloud-calendar


#+begin_example
he format of an iCloud caldav URL is as follows:

https://pXX-caldav.icloud.com/<DSid>/calendars/<pGUID>

#+end_example


#+begin_example

数年前に別のサイトで書いていた内容を2016年版として書き直してみました。

iCloudのカレンダーをLightningやSunbird等と同期させたい時、iCloudのCalDAVのURLが必要になります。 また、iCloudの連絡先(アドレス帳)にアクセスするにはiCloudのCardDAVのURLが必要になります。

以下、Chromeを使ってURLを調べる方法です。

    Chromeで https://www.icloud.com/ を開きます。

    メニューからデベロッパーツールを起動して(Windowsの場合F12を押せば起動)、Networkをクリックしておきます。

    iCloudにサインインします。

    Networkの検索窓にloginと打って検索します。

    一番上に名前がaccountLoginでPOSTしてる行が見つかるはずなのでクリックし、さらにPreviewをクリックします。

    ツリーの中から以下の情報を探し出し(ピリオドがツリーの区切り)、値をメモっておきます。

        dsInfo.dsid

        webservices.calendar.url

        webservices.contacts.url

    webservices.calendar.urlから、次のようにカレンダーのホスト名を求めます。

    https://pXX-calendarws.icloud.com:443(pXXのXXは数字)

    ↓↓↓↓

    https://pXX-calendars.icloud.com:443(calendarwsのwsをsにする)

    CalDAVのURLは以下のようになります。

        ホーム https://pXX-calendars.icloud.com/<dsInfo.dsid>/calendars/home/

        仕事 https://pXX-calendars.icloud.com/<dsInfo.dsid>/calendars/work/

        リマインダー https://pXX-calendars.icloud.com/<dsInfo.dsid>/calendars/tasks/

    標準以外のカレンダーのURLについてはiCloudの任意のカレンダーのCalDAVのURLを得る方法(2016年版)を参照してください。

    webservices.contacts.urlから、カレンダーと同様に連絡先のホスト名を求めます。

    https://pXX-contactsws.icloud.com:443(pXXのXXは数字)

    ↓↓↓↓

    https://pXX-contacts.icloud.com:443(contactswsのwsをとる)

    CardDAVのURLは以下のようになります。
        https://pXX-contacts.icloud.com/<dsInfo.dsid>/carddavhome/card/




#+end_example


https://p54-contactsws.icloud.com/co/mecard/?clientBuildNumber=1923Project57&

https://p54-calendarws.icloud.com/ca/alarmtriggers/?startDate=2020-01-06&endDate=2020-01-07&lang=zh-cn&usertz=Asia%2FShanghai&clientBuildNumber=1923Project57&clientMasteringNumber=1923B31&clientId=64c962e9-aa53-403d-bba4-604d77f3d9f6&dsid=16512278269
https://p54-remindersws.icloud.com/rd/alarmtriggers/?startDate=2020-01-06&endDate=2020-01-07&lang=zh-cn&usertz=Asia%2FShanghai&clientBuildNumber=1923Project57&clientMasteringNumber=1923B31&clientId=64c962e9-aa53-403d-bba4-604d77f3d9f6&dsid=16512278269



Request URL:https://p54-calendarws.icloud.com/ca/collections/home?clientBuildNumber=1923Project38&clientId=64c962e9-aa53-403d-bba4-604d77f3d9f6&clientMasteringNumber=1923B31&clientVersion=5.1&dsid=16512278269&endDate=2020-02-01&ifMatch=C%3D108%40U%3Df4695b88-a5de-415d-88c9-f17a4923a438&lang=zh-cn&methodOverride=PUT&requestID=6&startDate=2019-12-29&usertz=Asia%2FShanghai

Request URL:https://p54-calendarws.icloud.com/ca/collections/70570E18-F277-48BB-8B07-070B92E1D68E?clientBuildNumber=1923Project38&clientId=64c962e9-aa53-403d-bba4-604d77f3d9f6&clientMasteringNumber=1923B31&clientVersion=5.1&dsid=16512278269&endDate=2020-02-01&ifMatch=C%3D116%40U%3Df4695b88-a5de-415d-88c9-f17a4923a438&lang=zh-cn&methodOverride=PUT&requestID=10&startDate=2019-12-29&usertz=Asia%2FShanghai
* org --> ppt (pandoc)

** --slide-level 参数
 - https://pandoc.org/MANUAL.html
   Structuring the slide show

#+begin_example
 pandoc -f org -t pptx -o test.pptx  --slide-level=2 test.org
#+end_example


* xmind 8 
  现在只能在jdk8上能运行( java-8-openjdk)


* home 隐藏目录
  | 目录         | 备份   | 备注                                         |
  | .cache       | 不需要 | 缓存数据                                     |
  | .config      | 不需要 | 程序配置，自己的程序配置，自己备份，不在这里 |
  | .local       | 不需要 | 类似/usr/local                               |
  | .m2          | 不需要 |                                              |
  | .mozila      |        |                                              |
  | .thunderbird |        |                                              |
  | .zotero      |        |                                              |

* 需要备份的程序配置
  - firefox
  - thunderbir
  - zotero

* linux 多网口 变成交换机
  - iptables详解：iptables概念(写的不错，值得看)
    http://www.zsythink.net/archives/1199
  
** 使用NetworkManager命令行是可以工作的

   https://wiki.archlinux.org/index.php/Network_bridge

生成bridge
#+begin_src bash 
nmcli connection add type bridge ifname br0 stp no
#+end_src

Making interface enp30s0 a slave to the bridge: 

#+begin_src bash 
nmcli connection add type bridge-slave ifname enp30s0 master br0
#+end_src

Setting the existing connection as down:

#+begin_src bash 
nmcli connection down Connection
#+end_src

Setting the new bridge as up:

#+begin_src bash 
 nmcli connection up bridge-br0
#+end_src


ip link

#+begin_example
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: enp0s25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br0 state UP mode DEFAULT group default qlen 1000
    link/ether 3c:97:0e:44:b4:72 brd ff:ff:ff:ff:ff:ff
3: wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DORMANT group default qlen 1000
    link/ether 20:68:9d:f1:d8:3e brd ff:ff:ff:ff:ff:ff
4: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 6a:77:8a:ef:e0:d5 brd ff:ff:ff:ff:ff:ff
5: enp0s20u2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br0 state UP mode DEFAULT group default qlen 1000
    link/ether 30:b4:9e:ef:10:be brd ff:ff:ff:ff:ff:ff
#+end_example

** linux bridge
   https://goyalankit.com/blog/linux-bridge

#+begin_example

Linux bridge is a layer 2 virtual device that on its own cannot receive or transmit anything unless you bind one or more real devices to it. source.

As Anatomy of a Linux bridge puts it, bridge mainly consists of four major components:

    Set of network ports (or interfaces): used to forward traffic between end switches to other hosts in the network.
    A control plane: used to run Spanning Tree Protocol (STP) that calculates minimum spanning tree, preventing loops from crashing the network.
    A forwarding plane: used to process incoming input frames from the ports, forward them to the network port by making a forwarding decision based on the MAC learning database.
    MAC learning database: used to keep track of the host locations in the LAN.

For each unicast mac address, bridge maintains a mac learning database to decide which ports to forward based on MAC addresses, and if it can’t find an entry for a given mac address, it will broadcast the frame to all ports except the one where it received the frame from.

There are three main configuration subsystems to do bridges:

    ioctl: This interface is used to create/destroy bridges and add/remove interfaces to/from a bridge.
    sysfs: Management of bridge and port specific parameters.
    netlink: Asynchronous queue based communication that uses AF_NETLINK address family, can also be used to interact with bridge.

In this article, we only talk about ioctl.

#+end_example

#+begin_src bash 
pacman -S bridge-utils
#+end_src


  - linux bridge网桥的工作原理
https://blog.csdn.net/u014027051/article/details/53908878
  Bridge（桥）是 Linux 上用来做 TCP/IP 二层协议交换的设备，与现实世界中的交换机功能相似。
  - Linux实现交换机的另一种方法
    https://blog.csdn.net/sinat_20184565/article/details/80223749

   首先创建全局网桥br_test。将所有物理接口添加到网桥下。此时，相当于一个纯二层交换机。
    #+begin_example
    brctl addbr br_test
    brctl addif br_test eth0
    brctl addif br_test eth1

    #+end_example
    
** Bridging wlan0 to eth0

   - https://serverfault.com/questions/152363/bridging-wlan0-to-eth0


#+begin_src bash

 iw dev <wifiInterface> set 4addr on

#+end_src
** ebtables
** arp proxy 
   https://wiki.debian.org/BridgeNetworkConnectionsProxyArp

   
   路由里加的是与eth0在同一LAN内的主机IP, 而不是wlan一侧LAN的主机IP.
   
   #+begin_src bash 
   echo 1 > /proc/sys/net/ipv4/conf/all/proxy_arp
   echo 1 > /proc/sys/net/ipv4/ip_forward
   ip ro add 10.42.0.11/32 dev eth0 
   #+end_src

   自动化配置，　需要安装arp proxy软件。如果只是临时用一下，则不用安装，只要每次输入上面说的命令，配置即可。
     - parprouted 
     - parpd

   
** 通过ＡＰ访问外网
https://www.cnblogs.com/shineshqw/articles/2351028.html

#+begin_example
  echo 1 > /proc/sys/net/ipv4/ip_forward

  iptables -t nat -A POSTROUTING -s 192.168.8.0/24 -o eth0 -j SNAT --to 你的eth0地址
#+end_example
   
192.168.8.0 是ＡＰ的网段. 



* mp3 to wav

#+begin_example
ffmpeg -i

ffmpeg -i The\ Truth\ That\ You\ Leave-Pianoboy.mp3 -acodec pcm_u8 -ar 320000 The\ Truth\ That\ You\ Leave.wav
#+end_example

* thunderbird 使用外部编辑器
** exteditor
   https://github.com/exteditor/exteditor
   http://globs.org/articles.php?lng=en&pg=2

** Link directly to emails from Emacs Orgmode using Thunderbird and Thunderlink
   https://vxlabs.com/2019/04/20/link-thunderbird-emails-from-emacs-orgmode/
* 图片分辩率变小
  convert(imagemagick)
  - linux 用ImageMagick批量压缩图片形成缩略图

http://www.lao8.org/article_1698/imagemagick_linux.html



#+begin_src bash 

    for img in `ls *.jpg` ; do  convert -sample 25%x25% $img thumb-$img ; done
    #这个命令是批量缩小25%
#+end_src


#+begin_src bash 
 for img in `ls */*.jpg` ; do convert -resize "900 >" $img $img ; done 
#+end_src

 注： -resize 是缩小，-sample 是压缩 


 for img in `ls ../*.jpg` ; do convert -resize 50%x50% $img $img ; done 
 for img in `ls *.JPG` ; do convert -resize 25%x25% $img $img ; done 
